In [1]:
import pandas as pd
from sklearn.datasets import load_iris

def load_dataset():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['species'] = iris.target
    df['species_name'] = df.apply(
        lambda x: str(iris.target_names[int(x["species"])]),axis=1
    )
    return df

/Users/millicentomondi/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
load_dataset()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,species_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def train(df):
    X_train, X_test, y_train, y_test = train_test_split(
        df.iloc[:, :-1], df["species"], test_size=0.2, random_state=42
    )

    model = LogisticRegression(max_iter=200)
    model.fit(X_train, y_train)

    return model, X_train, X_test, y_train, y_test

def get_accuracy(model, X_test, y_test):
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    return accuracy

In [17]:
# Call the train function to get the model and split data
model, X_train, X_test, y_train, y_test = train(load_dataset())

# Call get_accuracy to compute the accuracy on the test set
accuracy = get_accuracy(model, X_test, y_test)

# Print the accuracy
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 100.00%

In [18]:
def test_load_dataset():
    df = load_dataset()
    assert not df.empty, "The DataFrame should not be empty after loading the dataset."

def test_model_accuracy():
    df = load_dataset()
    model, X_train, X_test, y_train, y_test = train(df)
    accuracy = get_accuracy(model, X_test, y_test)
    assert accuracy > 0.8, "Model accuracy is below 80%."